Реализован потокобезопасный массив ThreadSafeArray.
evtaa/FocusStartHomeworks pull request #3
Opened 2021-11-07 11:26 UTC by evtaa

Реализован потокобезопасный массив ThreadSafeArray, имеющий возможность работать с элементами любого типа. ThreadSafeArray имплементирует протокол  ThreadSafeArrayProtocol, который содержит обязательные методы в соответствии с ТЗ.
Для демонстрации результат добавлены две асинхронные задачи, добавления элементов в массив, в параллельную очередь. После завершения обоих задач, в консоль выводится количество элементов в массиве.

2021-11-08 17:08 UTC, AlexRaptor requested changes
Главный вопрос к инкапсуляции

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +let myGlobalQueue = DispatchQueue.global()
Создай свою очередь

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +func appendToArray(element: Type) {
Раз уж на то пошло, почему бы не сделать это generic-функцией?

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +protocol ThreadSafeArrayProtocol {
Вот есть этот протокол... и он говорит мне, что я могу добавлять в коллекцию элементы, удалять, брать по индексу, а так же узнавать пустоту и "размер".
А ещё он мне говорит, что я могу у коллекции взять какую-то очередь.
Ну и на последок получить "внутренности хранения".
И - инкапсуляция :)

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +    subscript(index: Int) -> Element? { get set }
возвращается опционал - это не критикл, это выбор разработчика, но например вот сабскрит массива от Apple
`subscript(index: Int) -> Element { get set }`

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +extension ThreadSafeArrayProtocol where Element: Equatable {
это по-умолчанию internal

2021-11-08 17:08 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +            guard let newValue = newValue,
А почему эта проверка не в барьере?

2021-11-08 19:40 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +let myGlobalQueue = DispatchQueue.global()
Создал.

2021-11-08 19:40 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +    subscript(index: Int) -> Element? { get set }
Исправил.

2021-11-08 19:40 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +            guard let newValue = newValue,
Исправил.

2021-11-08 19:41 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +func appendToArray(element: Type) {
Сделал.

2021-11-08 19:41 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +protocol ThreadSafeArrayProtocol {
Убрал лишние требования у протокола.

2021-11-08 19:43 UTC, evtaa commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +extension ThreadSafeArrayProtocol where Element: Equatable {
Исправил

2021-11-09 15:12 UTC, AlexRaptor requested changes
Давай честный generic-метод :)

2021-11-09 15:12 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +        guard let element = element as? Type
От этого непонятного каста можно избавиться, если прокидывать параметризованный массив внутрь как inout. А то это какой-то фэйковый получается generic - параметризовать можно, но работать будет только с одним определённым типом (ну или с несколькими, которые можно к нему скастить)

2021-11-10 04:16 UTC, AlexRaptor approved these changes
Хорошая работа!

2021-11-10 04:16 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +func appendToThreadSafeArray<T>(element: T, array: inout ThreadSafeArray<T>) {
У тебя есть в названии метода слово `array`, так что красивее было бы назвать так:
`func appendToThreadSafeArray<T>(_ array: inout ThreadSafeArray<T>, element: T) {`

2021-11-10 10:12 UTC, merged