Разработано приложение myCV.
evtaa/FocusStartHomeworks pull request #4
Opened 2021-11-14 19:49 UTC by evtaa

Разработано приложение, состоящее из трех UIViewController: персональная информация, рабочий профиль, интересы. Навигация осуществляется с помощью UITabBarController. Все экраны сверстаны полностью через код с помощью AutoLayout. Первый экран не содержит UIStackView. Данные выделены в отдельные сущности.

2021-11-15 11:26 UTC, c0dedbear requested changes
Приложение выглядит хорошо, покрутил во всех ориентациях - все отлично, единственно в темной теме segmentedControl выбивается.

Но твой пул было очень тяжело смотреть.
Во первых, ты запихал весь код в один коммит, во вторых ну слишком много кода для такого рода задания. 
Тебе нужно научиться понимать масштаб и выбирать соответствующие инструменты, пихать всякие экстеншены и дженерики просто для того чтобы они были плохая практика.

Есть мелкие замечания, и вопросики в некоторых моментах. Я не буду тут обсуждать архитектурные особенности, у вас будет отдельный блок по ним.

2021-11-15 11:26 UTC, c0dedbear commented on myCV/myCV/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
final и пустые методы и в SceneDelegate тоже самое

2021-11-15 11:26 UTC, c0dedbear commented on myCV/myCV/Common/Extension/Color.swift
> +    convenience init(hex: Int32) {
Выглядят как то оверхедно все эти сдвиги по битам, была реальная необходимость по hex цвет задать?)

2021-11-15 11:26 UTC, c0dedbear commented on myCV/myCV/Common/Factory/ViewModel/CommonInterestsViewModelFactory.swift
> +final class CommonInterestsViewModelFactory {
Общий вопрос по всем фабриками и ассемблям - чем оправдано использование класса? Ты их где то создаешь и используешь?

2021-11-15 11:26 UTC, c0dedbear commented on myCV/myCV/Modules/Profile/Controller/ProfileController.swift
> +extension ProfileController: UITableViewDelegate {
зачем конформить если не используется?

2021-11-15 13:33 UTC, evtaa commented on myCV/myCV/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
Сделал

2021-11-15 13:33 UTC, evtaa commented on myCV/myCV/Common/Extension/Color.swift
> +    convenience init(hex: Int32) {
Убрал

2021-11-15 13:35 UTC, evtaa commented on myCV/myCV/Common/Factory/ViewModel/CommonInterestsViewModelFactory.swift
> +final class CommonInterestsViewModelFactory {
В данном случае можно и структуру. Объекты классов не создаю. Использую статические методы класса.

2021-11-15 13:35 UTC, evtaa commented on myCV/myCV/Modules/Profile/Controller/ProfileController.swift
> +extension ProfileController: UITableViewDelegate {
Убрал

2021-11-15 13:39 UTC, evtaa commented
Экстеншены и джененрики добавлялись для уменьшения количества строк кода в контроллерах. Теперь в приложении не выбивается SegmentedControl в темной теме. Убрал final и пустые методы в AppDelegate и SceneDelegate. Убрал экстеншион для UIColor. Убрал не используемые делегаты.

2021-11-16 04:23 UTC, c0dedbear approved these changes
Принято

2021-11-16 04:23 UTC, merged