Feature/homework 4
evtaa/FocusStartHomeworks pull request #5
Opened 2021-11-20 13:45 UTC by evtaa

Создано приложение на основе UICollectionView. Сначала делал на основе UITableViewDataSource, потом переделал на DiffableDataSource. Приложение состоит из трех экранов. На первом экране отображается коллекция. На втором более детальная информация про изображения. При нажатии на изображение на экране деталей модально презентуется изображение с размером на весь экран.

2021-11-21 16:13 UTC, c0dedbear requested changes
Не хватает кнопки для закрытия на модальном экране. ( не юзер френдли), особенно в альбомной ориентации.

В этот раз спасибо, что бойлер-плейт кода поменьше 😄, но все равно он есть.

2021-11-21 16:13 UTC, c0dedbear commented on CollectionApp/CollectionApp/Commoon/Structures/Image.swift
> +    let id = NSUUID()
зачем здесь NSUUID если достаточно просто UUID?

2021-11-21 16:13 UTC, c0dedbear commented on CollectionApp/CollectionApp/Modules/DetailInfo/Assemble/DetailInfoAssembler.swift
> +final class DetailInfoAssembler {
"Ассемблеры" твои избыточны, у тебя ни зависимостей, ни параметров, вместо того чтобы просто вьюконтроллеры в одну строчку создавать там где надо, ты насоздавал классы которые делают тоже самое, только с 10 раз большим количеством кода.

2021-11-21 16:13 UTC, c0dedbear commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +typealias  DataSource  =  UICollectionViewDiffableDataSource < Section , Image >
многовато пробелов в этой строчке

2021-11-21 16:13 UTC, c0dedbear commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +        let vc = DetailInfoAssembler.assemble(with: image)
let vc = DetailInfoController(image: image) , это к слову об ассемблях, это даже не уменьшает количество кода.

2021-11-21 16:13 UTC, c0dedbear commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +    func applySnapshot (animatingDifferences: Bool = true) {
нет смысла тут анимировать у тебя данные не меняются

2021-11-21 20:36 UTC, evtaa commented on CollectionApp/CollectionApp/Commoon/Structures/Image.swift
> +    let id = NSUUID()
Согласен можно проще. Убрал NSUUID.

2021-11-21 20:38 UTC, evtaa commented on CollectionApp/CollectionApp/Modules/DetailInfo/Assemble/DetailInfoAssembler.swift
> +final class DetailInfoAssembler {
В данной реализации они избыточны. Обычно во вьюконтролер добавляются различные сервисы и данный сборщик в этих случаях актуален. Убрал сборщика.

2021-11-21 20:39 UTC, evtaa commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +typealias  DataSource  =  UICollectionViewDiffableDataSource < Section , Image >
Исправил. Торопился.

2021-11-21 20:39 UTC, evtaa commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +        let vc = DetailInfoAssembler.assemble(with: image)
Исправил

2021-11-21 20:40 UTC, evtaa commented on CollectionApp/CollectionApp/Modules/ImagesCollection/Controller/ImagesCollectionController.swift
> +    func applySnapshot (animatingDifferences: Bool = true) {
Согласен, в данном случае анимацию можно убрать. Убрал.

2021-11-21 20:44 UTC, evtaa commented
Изначально показалось странным презентовать контроллер модально, а потом добавлять на него кнопку для его закрытия. 
Не проще ли сразу добавлять контроллер в UINavigation стек, где есть кнопка возврата уже по умолчанию? 
А каком бойлер плейте идет речь?

Добавил кнопку для закрытия на модальном экране.

2021-11-22 16:41 UTC, c0dedbear commented
> Изначально показалось странным презентовать контроллер модально, а потом добавлять на него кнопку для его закрытия. Не проще ли сразу добавлять контроллер в UINavigation стек, где есть кнопка возврата уже по умолчанию? А каком бойлер плейте идет речь?
> 
> Добавил кнопку для закрытия на модальном экране и исправил все замечания.

1. Модальный экран на то модально открывается, чтобы быть не в стеке. У тебя экран может быть вообще без navigationController'a. Странно то, что модальные экраны кажутся тебе странными, если проще все в стек пихать...
2. Тот код который ты удалил например.

2021-11-22 16:42 UTC, c0dedbear approved these changes
Принято

2021-11-22 16:42 UTC, merged