Feature/homework 8
evtaa/FocusStartHomeworks pull request #9
Opened 2021-12-19 01:45 UTC by evtaa

Разработано приложение состоящее из пяти экранов. Экраны написаны на основе MVP (вью пассивная).  На первом экране отображается список компаний. Данные хранятся в базе данных. Для работы с базой данных используется CoreData. При нажатии на кнопку «Add» можно добавить компанию в базу данных.  Список компаний обновляется после добавления. Компанию можно добавить или удалить. При удалении компании удаляюся все ее сотрудники. 
При нажатии на компанию в таблице отображается список сотрудников компании. При нажатии на кнопку добавить можно добавить сотрудника в компанию. Список сотрудников обновляется после добавления. При нажатии на сотрудника в таблицу можно отредактировать его данные. При удалении сотрудника удаляется его ссылка на компанию.

2021-12-20 09:41 UTC, AlexRaptor requested changes
- [ ] безработных быть не может - поле не должно быть опциональным
- [ ] стаж должен быть опциональным
Скопипащен целый модуль! Редактирование и создание сотрудника - это почти одно и то же с маленьким отличием. Это можно не править, но понимать нужно.

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/CoreDataService/CoreDataManager.swift
> +        let container = NSPersistentContainer(name: "_ompanyEmployees")
А чего название с подчерком? Xcode заменил, потому что в названии проекта `СompanyEmployees` первая буква русская? :)

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var company: Company?
По условию безраборных быть не может

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var experience: Int32
А вот стаж опциональный

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/Model/AddCompanyModel.swift
> +final class  AddCompanyModel {
Что это и зачем? Зачем оно в презентере?

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/Router/ AddCompanyRouter.swift
> +//   AddCompanyRouter.swift
Название файла начинается с пробела

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Application/SceneDelegate.swift
> +        guard let companyStorage = self.coreDataManager as? ICompanyStorage
Не понятно зачем такие приседания с кастом...
```swift
let coreDataManager = CoreDataManager()
self.coreDataManager = coreDataManager
let vc = ListCompanyAssembler.assemble(companyStorage: coreDataManager)
```

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Classes/EmployeeViewModel.swift
> +    var experience: String { get set }
опционал

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Classes/EmployeeModel.swift
> +    init(uid: UUID, companyUid: UUID, name: String, age: Int, experience: Int?) {
неиспользуемый код

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +        let experienceModel: String
Что такое `experienceModel` ? Почему тогда просто `name` и `age`, а не `nameModel` и `ageModel` ?

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +        if let experience = employee.experience {
Есть оператор `??`

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +            experienceModel = "0"
нулевой стаж и отсутствие информации о стаже - разные вещи

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/View/AddCompanyView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
как по мне, так установка `translatesAutoresizingMaskIntoConstraints` относится к нестройке layout-а, и должна быть там

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/Classes/CompanyViewModel.swift
> +struct CompanyViewModel {
Это моделька для вью. У тебя экраны - модули. Значит место этой модельки в модуле, где она используется.
И ещё: папка `Classes`... что в ней лежит, классы? Почему тогда не все классы?

2021-12-20 09:41 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/CoreDataService/CoreDataManager.swift
> +import UIKit
Зачем данным знать об интерфейсе?

2021-12-20 11:33 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var experience: Int32
При попытке назначить Int32 выдает ошибку: "Property cannot be marked @NSManaged because its type cannot be represented in Objective-C"

2021-12-20 11:37 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/Model/AddCompanyModel.swift
> +final class  AddCompanyModel {
По сути здесь он не нужен. Остался от шаблона MVP. Удаляю.

2021-12-20 12:20 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/View/AddCompanyView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
А это разве не вопрос вкусовщины. Исправил во всем проекте.

2021-12-20 12:26 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Classes/CompanyViewModel.swift
> +struct CompanyViewModel {
Теперь лежат все классы, а моделька перенесена в модуль.

2021-12-20 12:28 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/CoreDataService/CoreDataManager.swift
> +import UIKit
Незачем. Закрался враг в тылу. Убрал.

2021-12-20 12:35 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/CoreDataService/CoreDataManager.swift
> +        let container = NSPersistentContainer(name: "_ompanyEmployees")
Исправил. Не знаю почему так было. Действительно возможно из за того что была русская буква.

2021-12-20 12:35 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var company: Company?
Исправил

2021-12-20 12:36 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +        if let experience = employee.experience {
Исправил

2021-12-20 12:46 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/Router/ AddCompanyRouter.swift
> +//   AddCompanyRouter.swift
Исправил

2021-12-20 12:54 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var experience: Int32
https://developer.apple.com/forums/thread/61294

2021-12-20 12:59 UTC, AlexRaptor commented on СompanyEmployees/СompanyEmployees/Modules/AddCompany/View/AddCompanyView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
Я бы не сказал, что это вкусовщина на 100% по нескольким причинам:
- это относится к layout-у и есть отдельный метод а-ля `configureLayout()` - значит место там
- если будет затащен какой-нить layout-фреймворк типа SnapKit-а (а они сами конфигурят `translatesAutoresizingMaskIntoConstraints`), то проще будет внести изменения в один метод, чем вылавливать по всему коду, где ещё конфигурится вёрстка

2021-12-20 15:59 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +        let experienceModel: String
Добавил

2021-12-20 16:00 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Classes/EmployeeModel.swift
> +    init(uid: UUID, companyUid: UUID, name: String, age: Int, experience: Int?) {
Убрал

2021-12-20 16:00 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Classes/EmployeeViewModel.swift
> +    var experience: String { get set }
Добавил

2021-12-20 16:01 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Application/SceneDelegate.swift
> +        guard let companyStorage = self.coreDataManager as? ICompanyStorage
Да приседы абсолютно лишние. Убрал.

2021-12-20 16:02 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/Factory/EmployeeViewModelFactory.swift
> +            experienceModel = "0"
ИСправил

2021-12-20 16:48 UTC, evtaa commented on СompanyEmployees/СompanyEmployees/Common/CoreDataObjects/Employee+CoreDataProperties.swift
> +    @NSManaged public var experience: Int32
Исправил.

2021-12-20 17:02 UTC, evtaa commented
Изменил название проекта. Теперь безработных нет. Experience теперь имеет тип NSNumber. Удален лишний код. Там где нужно добавлен опционал. В файлах там где не нужно убран импорт библиотек. Теперь вью модели лежат в модулях.

2021-12-21 02:44 UTC, AlexRaptor approved these changes

2021-12-27 12:11 UTC, merged